packages:
  - name: frost
    environment: {}
    parameters: {}
    actions:
      - name: frost
        main: ''
        runtime: 'go:default'
        environment:  
          APIKEY : "${APIKEY}"

